### ISSUE TITLE
AttributeError exception to be catched

### ISSUE THREAD

**Issue by nchiarappa** [nchiarappa/tidal-spotify-converter#1]
When copying tidal playlists from one account to another one

Traceback (most recent call last):
  File "script.py", line 417, in <module>
    copy_tidal_playlists_to_another_tidal_account()
  File "script.py", line 163, in copy_tidal_playlists_to_another_tidal_account
    tracks = tidal_session_2.get_playlist_tracks(playlist.id)
  File "/home/nicola/.local/lib/python2.7/site-packages/tidalapi/__init__.py", line 113, in get_playlist_tracks
    return self._map_request('playlists/%s/tracks' % playlist_id, ret='tracks')
  File "/home/nicola/.local/lib/python2.7/site-packages/tidalapi/__init__.py", line 189, in _map_request
    return list(map(parse, items))
  File "/home/nicola/.local/lib/python2.7/site-packages/tidalapi/__init__.py", line 256, in _parse_track
    album = _parse_album(json_obj['album'], artist)
  File "/home/nicola/.local/lib/python2.7/site-packages/tidalapi/__init__.py", line 226, in _parse_album
    kwargs['release_date'] = datetime.datetime(*map(int, json_obj['releaseDate'].split('-')))
AttributeError: 'NoneType' object has no attribute 'split'

In tidalapi only ValueError exception is handled (see https://pythonhosted.org/tidalapi/_modules/tidalapi.html#Session.get_playlist_tracks and related _parse_album method).

**Comment by nchiarappa** [comment]
Change
except (ValueError, AttributeError) as e:
    pass
should be done in tidalapi
